### ISSUE TITLE
Design Dashboard page

### ISSUE THREAD

**Issue by Swadeshit27** [Swadeshit27/Admin-panel-frontend#1]
In the dashboard page, you have to show total products, total category, total customers, notifications we have. And show a revenue chart as well.
you can help to this video to design this page - https://youtu.be/pWd29MtFGJA?si=lx6DkMdc5YffCVXH

Design this page just like below .
![image](https://github.com/Swadeshit27/Admin-panel-frontend/assets/97722877/a2eac212-917d-4b25-bcfb-e99f0a274454)

**Comment by Ananyamishra08** [comment]
If you will give me this problem, I think I could breathe new life into it. It looks interesting. Awaiting to get assigned from @Swadeshit27 on or after Jan 15.

**Comment by ayesha-2101** [comment]
I am willing to work for this. Please assign this to me @Swadeshit27

**Comment by Hacxmr** [comment]
Hey! @Swadeshit27, I am interested in contributing to this issue. Can you assign me this under JWOC'24?

**Comment by Hacxmr** [comment]
Thanks for considering. I will update you soon regarding the changes and updates

**Comment by DarshSohaliya** [comment]
I would like to work on that issue under JWOC 2024

**Comment by Hacxmr** [comment]
I have made a PR. Suggest any further changes if required.
