### ISSUE TITLE
Changing tab icon to admin logo 

### ISSUE THREAD

**Issue by ajitgavadegit** [Swadeshit27/Admin-panel-frontend#18]
Issue : On live projet showing vite logo at tab icon 
Improvement : I would like to change this icon to a classic admin icon to improve UI for admin panel 
Note : We can use cassis icon or admin can suggest incase.
:: I would like to contribute in this issue Please assign this under JWOC

**Comment by ajitgavadegit** [comment]
Hey @Swadeshit27  I changed tab-icon
Please respond on PR
![Screenshot (590)](https://github.com/Swadeshit27/Admin-panel-frontend/assets/94741808/03e5162b-2a50-40eb-9d79-911073cc5941)

**Comment by ajitgavadegit** [comment]
@Swadeshit27  Need help 

> PS D:\OpenSource\Admin-panel-frontend> git push -u origin "tab-icon"        
> ERROR: Permission to Swadeshit27/Admin-panel-frontend.git denied to actron-git.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

This is showing while making push command can u help me out.
I made necessary changes in PR

**Comment by Swadeshit27** [comment]
you entered wrong command
follow this steps
git add . 
git commit -m "Your message" 
git pull  
git push -u origin your-branch-name

**Comment by ajitgavadegit** [comment]
@Swadeshit27  I made PR please make conformation , Hope this time I did correct command. And thank you for help.

**Comment by ajitgavadegit** [comment]
Hey @Swadeshit27  can u check PR I resolved conflict. Please make review and convey.
