### ISSUE TITLE
Design products page

### ISSUE THREAD

**Issue by Swadeshit27** [Swadeshit27/Admin-panel-frontend#4]
Design a products table contains these fields -  id, poducts name, photo,descriptions,category, price, discount, actions(edit/delete). Design  like as I mention in customer page issue. In the top of the table create add new products button. If the button is clicked then a from will open and the form contains these fields.

**Comment by shahil-afroz** [comment]
So we have to create an web page contains table and a button .This button  helps user to create new table of products. Am I right?
but where I connect the web page ???

**Comment by Sruti-sahini** [comment]
Hello @Swadeshit27!
I am from JWoC'24
I have a good hold on web development.
Could you please assign me tis issue after the coding period starts?

**Comment by Swadeshit27** [comment]
@shahil-afroz  Yes just like that If the button is clicked then a new form will open in the same page just like popup just like below.
![image](https://github.com/Swadeshit27/Admin-panel-frontend/assets/97722877/a495db38-d57a-4e61-910e-e40619e83dde)

If anyone don't understand what am I say let me know, I will send some references.

**Comment by Hrx4** [comment]
@Swadeshit27   is there any figma file available ? if yes then assign this issue to me under JWOC

**Comment by Swadeshit27** [comment]
@Hrx4 I don't have any figma design you have to design your own.

**Comment by vermaanurag1532** [comment]
i can resolve this issue for you assign it to me

**Comment by Swadeshit27** [comment]
those who are working on this issue include "under JWOC " else I don't assign them

**Comment by vermaanurag1532** [comment]
i am working under jwoc please assign it to me

**Comment by swetasingh8844** [comment]
@Swadeshit27 please assign this issue to me under JWOC'24

**Comment by Hacxmr** [comment]
Hey! @Swadeshit27 I am interested in working on this issue. Kindly assign me this under JWOC.

**Comment by vermaanurag1532** [comment]
please Assign it to me
