### ISSUE TITLE
Add Dark mode and light mode functionality

### ISSUE THREAD

**Issue by Swadeshit27** [Swadeshit27/Admin-panel-frontend#5]

**Comment by debuuuu007** [comment]
I would like to work on this under JWOC'24

**Comment by Divyanshgarg-04** [comment]
@Swadeshit27 I would like to work on this issue under JWOC'24. Please assign this to me

**Comment by shahil-afroz** [comment]
please assign this issue to me......I would like to work on this under  JWOC 24...

**Comment by Hrx4** [comment]
Hey @Swadeshit27   assign this issue to me under JWOC

**Comment by Swadeshit27** [comment]
@shahil-afroz  you have to complete this task within 1 day else I will assign this issue to the next mentee.

**Comment by skj1709** [comment]
Hi @Swadeshit27 if this issue is still open then I would like to work on it. Under JWOC

**Comment by Swadeshit27** [comment]
@sumit-kumar-jha1709   you can start working on that issue.

**Comment by skj1709** [comment]
@Swadeshit27 Onto it.

**Comment by skj1709** [comment]
Hi @Swadeshit27 the points are not showing at the leaderboard of JWOC
